### PR TITLE
fix: fixed over-writing of gitignore file

### PR DESCRIPTION
**Pull request by Savio629**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x} Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #2 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by Savio629** [comment]
// @techsavvyash @sooraj1002

**Review by techsavvyash — CHANGES_REQUESTED** [review]
The changes look good. Please rebase the PR to `dev` branch.

**Comment by Savio629** [comment]
// @sooraj1002

**Comment by sooraj1002** [comment]
@Savio629 we need to add `.env` to the default `.gitignore`. after your change, that is not present as npx prisma init adds that to the gitignore and we are overwriting it

**Comment by Savio629** [comment]
so we need to merge the .gitignore instead of replacing it?
or should I just add .env under our default .gitignore file ?

**Comment by sooraj1002** [comment]
you can just add to the default `.gitignore`

**Comment by Savio629** [comment]
// @sooraj1002

**Comment by sooraj1002** [comment]
looks good

**Pull request merged**
