### PR TITLE
fix: updated aliases to work while bootstrapping a new project

### PR DESCRIPTION
**Pull request by Savio629**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by Savio629** [comment]
@sooraj1002 @techsavvyash

**Comment by techsavvyash** [comment]
Can you share a video showing that this works now?

**Comment by Savio629** [comment]
https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/099fd2d6-890d-46bb-a939-bb6670ef94e2

**Comment by sooraj1002** [comment]
looks good to me

**Pull request merged**
