### PR TITLE
Added Registry

### LINKED ISSUE #1: [cli] Registry for cli
## Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

## Description

Add a registry in the stencil cli to track what all things that a particular user is using.

### PR DESCRIPTION
**Pull request by Savio629**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by Savio629** [comment]
image

Generating .stencil file and then showing to the user

Any changes in the console log?

// @sooraj1002 @techsavvyash

**Comment by techsavvyash** [comment]
The log looks good, but why is showing an error in the last line of the console?

**Comment by Savio629** [comment]
if we come out of the stencil project, `.stencil` is not found so throwing .stencil not found error
also as there can be a lot of projects so running `stencil ls` inside project folder to avoid duplicates is necessary

**Comment by techsavvyash** [comment]
Is the PR done? @Savio629

**Comment by Savio629** [comment]
Does this output look fine?
https://github.com/SamagraX-Stencil/stencil-cli/pull/20#issuecomment-2034548680

**Comment by techsavvyash** [comment]
The output looks fine for the first iteration, how does the `.stencil` file look?

**Comment by Savio629** [comment]
The contents of .stencil file looks same as the `stencil ls` output

**Comment by sooraj1002** [comment]
Looks good

**Pull request merged**
