### PR TITLE
feat: added support for bun

### LINKED ISSUE #4: [stencil] [C4GT] Add support for bun
# Add Runtime Support for Bun in Stencil NestJS Project

## Description

With the integrated support for NestJS in Bun, the task is to extend the runtime options in Stencil. Users should have the flexibility to choose between two supported runtimes: NodeJS and BunJS.

### Goals

1. **Bun Runtime Integration:** Successfully integrate BunJS as a supported runtime in the Stencil NestJS project.

2. **User Runtime Selection:** Allow users to choose between the two supported runtimes (NodeJS and BunJS) for executing Stencil.

## Acceptance Criteria

1. **BunJS Integration:** Implement the necessary configurations and adjustments to seamlessly integrate BunJS as a runtime in the Stencil NestJS project.

2. **Runtime Selection:** Implement a user-friendly mechanism to select the desired runtime (NodeJS or BunJS) when running Stencil.

3. **Testing:** Ensure that both NodeJS and BunJS runtimes are functional and can successfully execute Stencilt.

4. **Documentation Update:** Provide comprehensive documentation on your work. Include it in the form of a READMe.md in your PR. It will be added to the official Stencil Docs

### Checklist (To be filled by the developer)

- [ ] Integrate BunJS as a supported runtime in the Stencil NestJS project.
- [ ] Implement a user-friendly mechanism for selecting runtimes.
- [ ] Test both NodeJS and BunJS runtimes to ensure functionality.
- [ ] Update documentation to include details about the new runtime options and selection process.

## Product Name 
Stencil

## Organisation Name
SamagraX

## Tech Skills Needed
Nodejs, Bun

## Mentors
@RyanWalker277  

## Complexity
Medium

## Category
Backend

## Sub Category
Nodejs

### PR DESCRIPTION
**Pull request by Savio629**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
There was runtime based on npm,pnpm and yarn.

Issue Number: # 4 -> https://github.com/SamagraX-Stencil/stencil/issues/4 

## What is the new behavior?
Added support for bun (1.0.35)

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by Savio629** [comment]
@techsavvyash 

Test results after adding bun:
my-stencil-test

Test results before adding bun:
stencil-cli-test


Issue is with schematics folder:
image

### Should I change @nestjs to @samagra-x, which will pass the test ?

**Comment by techsavvyash** [comment]
Yes, please make this change.

**Comment by Savio629** [comment]
After the changes, all test passes successfully 👍
image

**Review by techsavvyash — APPROVED** [review]

**Comment by techsavvyash** [comment]
Super work @Savio629 👏🏻

**Pull request merged**
