### PR TITLE
Created the workflow for pull requests to test before run #26

### PR DESCRIPTION
**Pull request by vishalmaurya850**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #26 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Summary by CodeRabbit

- **New Features**
	- Introduced an automated GitHub Actions workflow for testing pull requests targeting multiple branches, enhancing code quality and compatibility across various Node.js versions.
	- Added a badge to the README for real-time visibility of pull request test statuses, improving transparency and user engagement.

### CODE REVIEW

**Comment by vishalmaurya850** [comment]
I have merged the pull request please review it.

**Comment by Savio629** [comment]
@vishalmaurya850 Can you share a photo or an video of creating a pr and then the workflow getting trigger and generating the report?

**Comment by Savio629** [comment]
Also rebase the branch to `dev`

**Comment by vishalmaurya850** [comment]
ok

**Review by techsavvyash — APPROVED** [review]

**Pull request merged**
