### PR TITLE
fix: .env creation with prisma initialization 

### PR DESCRIPTION
**Pull request by Savio629**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #10 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by Savio629** [comment]
https://github.com/SamagraX-Stencil/stencil-cli/assets/91362589/132f082d-e923-4a36-addb-2177187f52b3

//  @sooraj1002 @techsavvyash

**Review by techsavvyash — CHANGES_REQUESTED** [review]
The changes look good. Please rebase the PR to `dev` branch.

**Comment by Savio629** [comment]
// @sooraj1002

**Comment by sooraj1002** [comment]
@Savio629 can we start `NODE_ENV`  from a newline?
image

**Comment by Savio629** [comment]
Oops, I'll fix that

**Comment by Savio629** [comment]
@sooraj1002

**Comment by sooraj1002** [comment]
could you please rebase this on dev @Savio629

**Comment by Savio629** [comment]
done

**Pull request merged**
